In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [28]:
dataset=pd.read_excel("/content/spam_detection_dataset.xlsx")

In [29]:
dataset

,word_freq_free,word_freq_money,word_freq_offer,word_freq_click,char_freq_$,char_freq_!,capital_run_length_avg,capital_run_length_longest,capital_run_length_total,class
0,0.03,0.09,0.05,0.04,0.02,0.01,2.00,19,68,0
1,0.68,0.63,0.82,0.37,0.18,0.20,6.89,92,319,1
2,0.03,0.03,0.04,0.02,0.00,0.02,1.20,19,59,0
3,0.75,0.69,0.53,0.51,0.12,0.05,6.52,75,306,1
4,0.08,0.01,0.02,0.04,0.02,0.00,2.66,21,59,0
...,...,...,...,...,...,...,...,...,...,...
495,0.01,0.08,0.01,0.02,0.01,0.01,1.44,9,57,0
496,0.01,0.00,0.02,0.02,0.01,0.01,1.77,23,12,0
497,0.08,0.00,0.02,0.04,0.00,0.01,2.98,18,43,0
498,0.09,0.02,0.02,0.04,0.01,0.01,1.21,17,15,0
499,0.06,0.07,0.09,0.01,0.01,0.02,1.91,25,66,0

In [30]:
dataset.isnull().sum()

word_freq_free                0
word_freq_money               0
word_freq_offer               0
word_freq_click               0
char_freq_$                   0
char_freq_!                   0
capital_run_length_avg        0
capital_run_length_longest    0
capital_run_length_total      0
class                         0
dtype: int64

In [31]:
print(dataset.head())

   word_freq_free  word_freq_money  word_freq_offer  word_freq_click  \
0            0.03             0.09             0.05             0.04
1            0.68             0.63             0.82             0.37
2            0.03             0.03             0.04             0.02
3            0.75             0.69             0.53             0.51
4            0.08             0.01             0.02             0.04

   char_freq_$  char_freq_!  capital_run_length_avg  \
0         0.02         0.01                    2.00
1         0.18         0.20                    6.89
2         0.00         0.02                    1.20
3         0.12         0.05                    6.52
4         0.02         0.00                    2.66

   capital_run_length_longest  capital_run_length_total  class
0                          19                        68      0
1                          92                       319      1
2                          19                        59      0
3                          75                       306      1
4                          21                        59      0

In [32]:
X = dataset.drop("class", axis=1)
y = dataset["class"]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [34]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
y_pred = model.predict(X_test)

In [36]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 1.0